fixtures:
  repositories:
    "augeas_core": "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    provision: "git://github.com/puppetlabs/provision.git"
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
  symlinks:
    "randrust": "#{source_dir}"
    "my_randrust": "#{source_dir}/spec/fixtures/my_randrust"
