version: '3'
services:
  app:
    build: .
    networks:
      - webapp
  nginx:
    image: nginx
    ports:
    - "443:443"
    environment:
    - APPLICATION_URL=http://app:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/test:/ssl
    networks:
      - webapp
networks:
  webapp: