version: '3'
services:
  app:
    build: .
    image: ryanjarv/randrust:latest
    networks:
      - randrust
  nginx:
    image: nginx
    ports:
    - "443:443"
    - "80:80"
    environment:
    - APPLICATION_URL=http://app:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/test:/ssl
    networks:
      - randrust
networks:
  randrust:
