#!/bin/sh
# Borrowed from https://github.com/mmstick/cargo-deb/issues/100#issuecomment-512253134

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask randrust.service >/dev/null
	fi
fi