#!/bin/sh

set -e

# Automatically added by dh_installinit/11.1.6ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d randrust remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_apparmor/2.12-4ubuntu5
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.local.bin.randrust" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.local.bin.randrust" || true
    rm -f "/etc/apparmor.d/force-complain/usr.local.bin.randrust" || true
    rm -f "/etc/apparmor.d/local/usr.local.bin.randrust" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'randrust.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'randrust.service' >/dev/null || true
		deb-systemd-helper unmask 'randrust.service' >/dev/null || true
	fi
fi
# End automatically added section